Reservation errors on save
kesslerd/dotnet_testat pull request #70
Opened 2017-12-13 15:31 UTC by kesslerd

2017-12-13 21:07 UTC, kesslerd commented
nur  der letzt commit ist neu, die andern sind bereits im pull 68 drin

2017-12-15 20:22 UTC, McDonnough requested changes

2017-12-15 20:22 UTC, McDonnough commented on AutoReservation.UI/Resources/Strings.xaml
>      <system:String x:Key="message_error_save_reservation_message">Der Reservation konnte nicht gespeichert werden. Kunde wurde neu geladen, bitte erneut ändern</system:String>
Müsste der hintere Teil nicht auch auf "Reservation" statt "Kunde" lauten?

2017-12-15 20:22 UTC, McDonnough commented on AutoReservation.UI/Resources/Strings.xaml
>      <system:String x:Key="message_error_delete_reservation_message">Der Reservation konnte nicht gelöscht werden. Kunde wurde neu geladen, bitte erneut löschen</system:String>
Müsste der hintere Teil nicht auch auf "Reservation" statt "Kunde" lauten?

2017-12-15 20:22 UTC, McDonnough commented on AutoReservation.UI/Views/Reservation.xaml.cs
> +            ViewModel.OnSaveErrorDateRange += (s, e) => MessageBox.Show((string)Application.Current.TryFindResource("message_error_save_resetvation_message_date"), (string)Application.Current.TryFind
Typo: "message_error_save_rese**t**vation_message_date"

2017-12-15 20:22 UTC, McDonnough commented on AutoReservation.UI/Resources/Strings.xaml
> +    <system:String x:Key="message_error_save_resetvation_message_auto">Auto not available.</system:String>
Typo: "message_error_save_rese**t**vation_message_date"

2017-12-15 20:27 UTC, McDonnough approved these changes

2017-12-15 20:27 UTC, merged